/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fbms.fbmsjframe;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.SQLException;
import javax.swing.JOptionPane; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import java.awt.geom.RoundRectangle2D;
/**
 *
 * @author Izee
 */
public class OpenJframe extends javax.swing.JFrame {
    
    // Log in panel instance
    private String signInUN, signInPass;
    private String signName, signUpUN, signUpPass;
    private String joinFamName, joinFamID; 
    private String createFamName;
    
    private NewJFrame jFrame;
    private FamilyBank fm, fmSU;
    
   
    public OpenJframe() {
        fm = new FamilyMember();
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hideTabPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        openAppPanel = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        openTitleText = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        signInPanel = new javax.swing.JPanel();
        signInTitle = new javax.swing.JLabel();
        signInUsernameLabel = new javax.swing.JLabel();
        signInUsernameTextfield = new javax.swing.JTextField();
        signInUsernameLabel1 = new javax.swing.JLabel();
        signInPasswordTextfield = new javax.swing.JTextField();
        signInSubmitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        signUpTitle = new javax.swing.JLabel();
        signUpPasswordLabel = new javax.swing.JLabel();
        signUpPasswordTextfield = new javax.swing.JTextField();
        signUpSubmitButton = new javax.swing.JButton();
        signUpUsernameLabel = new javax.swing.JLabel();
        signUpUsernameTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        signUpUsernameLabel1 = new javax.swing.JLabel();
        backButton2 = new javax.swing.JButton();
        isAMemberOfFamilyPanel = new javax.swing.JPanel();
        isAMemberOfFamilyCreateButton = new javax.swing.JButton();
        isAMemberOfFamilyJoinButton = new javax.swing.JButton();
        isAMemberOfFamilyTitle1 = new javax.swing.JLabel();
        isAMemberOfFamilyTitle2 = new javax.swing.JLabel();
        isAMemberOfFamilyTitle3 = new javax.swing.JLabel();
        backButtonToSignUp = new javax.swing.JButton();
        joinFamilyPanel = new javax.swing.JPanel();
        joinFamilyTitle = new javax.swing.JLabel();
        joinFamilySubmitButton = new javax.swing.JButton();
        joinFamilyIDLabel = new javax.swing.JLabel();
        joinFamilyIDTextfield = new javax.swing.JTextField();
        backButtonToQuestion = new javax.swing.JButton();
        createFamilyPanel = new javax.swing.JPanel();
        createFamilySubmitButton = new javax.swing.JButton();
        createFamilyTitle = new javax.swing.JLabel();
        createFamilyNameLabel = new javax.swing.JLabel();
        createFamilyNameLabelTextfield = new javax.swing.JTextField();
        buttonBackToQuestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Family Management System");
        setAutoRequestFocus(false);
        setName("openApplicationJframe"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hideTabPanel.setBackground(new java.awt.Color(0, 0, 48));

        exitButton.setBackground(new java.awt.Color(230, 68, 86));
        exitButton.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(210, 210, 215));
        exitButton.setText("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hideTabPanelLayout = new javax.swing.GroupLayout(hideTabPanel);
        hideTabPanel.setLayout(hideTabPanelLayout);
        hideTabPanelLayout.setHorizontalGroup(
            hideTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hideTabPanelLayout.createSequentialGroup()
                .addGap(0, 455, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hideTabPanelLayout.setVerticalGroup(
            hideTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hideTabPanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(exitButton))
        );

        getContentPane().add(hideTabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jTabbedPane.setBackground(new java.awt.Color(0, 0, 48));
        jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane.setPreferredSize(new java.awt.Dimension(500, 200));

        openAppPanel.setBackground(new java.awt.Color(0, 0, 48));
        openAppPanel.setName(""); // NOI18N
        openAppPanel.setPreferredSize(new java.awt.Dimension(500, 250));

        welcomeText.setFont(new java.awt.Font("Montserrat", 2, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(210, 210, 215));
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Welcome to");

        openTitleText.setFont(new java.awt.Font("Montserrat Black", 1, 27)); // NOI18N
        openTitleText.setForeground(new java.awt.Color(210, 210, 215));
        openTitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        openTitleText.setText("Family Management System ");

        signUpButton.setBackground(new java.awt.Color(210, 210, 215));
        signUpButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(38, 38, 38));
        signUpButton.setText("Sign Up");
        signUpButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        signInButton.setBackground(new java.awt.Color(89, 228, 147));
        signInButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        signInButton.setForeground(new java.awt.Color(38, 38, 38));
        signInButton.setText("Sign In");
        signInButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openAppPanelLayout = new javax.swing.GroupLayout(openAppPanel);
        openAppPanel.setLayout(openAppPanelLayout);
        openAppPanelLayout.setHorizontalGroup(
            openAppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openAppPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(openAppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openAppPanelLayout.createSequentialGroup()
                        .addComponent(openTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openAppPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(openAppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openAppPanelLayout.createSequentialGroup()
                                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openAppPanelLayout.createSequentialGroup()
                                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153))))))
        );
        openAppPanelLayout.setVerticalGroup(
            openAppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openAppPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(openAppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab1", openAppPanel);

        signInPanel.setBackground(new java.awt.Color(0, 0, 48));
        signInPanel.setPreferredSize(new java.awt.Dimension(500, 250));

        signInTitle.setFont(new java.awt.Font("Montserrat Black", 1, 27)); // NOI18N
        signInTitle.setForeground(new java.awt.Color(210, 210, 215));
        signInTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signInTitle.setText("Sign In");

        signInUsernameLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        signInUsernameLabel.setForeground(new java.awt.Color(210, 210, 215));
        signInUsernameLabel.setText("Username: ");

        signInUsernameTextfield.setBackground(new java.awt.Color(210, 210, 215));
        signInUsernameTextfield.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        signInUsernameTextfield.setForeground(new java.awt.Color(38, 38, 38));
        signInUsernameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInUsernameTextfieldActionPerformed(evt);
            }
        });

        signInUsernameLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        signInUsernameLabel1.setForeground(new java.awt.Color(210, 210, 215));
        signInUsernameLabel1.setText("Password:");

        signInPasswordTextfield.setBackground(new java.awt.Color(210, 210, 215));
        signInPasswordTextfield.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        signInPasswordTextfield.setForeground(new java.awt.Color(38, 38, 38));
        signInPasswordTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInPasswordTextfieldActionPerformed(evt);
            }
        });

        signInSubmitButton.setBackground(new java.awt.Color(89, 228, 147));
        signInSubmitButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        signInSubmitButton.setForeground(new java.awt.Color(38, 38, 38));
        signInSubmitButton.setLabel("Submit");
        signInSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInSubmitButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(236, 172, 116));
        backButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(38, 38, 38));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signInPanelLayout.createSequentialGroup()
                            .addComponent(signInUsernameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(signInUsernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPanelLayout.createSequentialGroup()
                            .addComponent(signInUsernameLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(signInPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signInPanelLayout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signInSubmitButton)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(signInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addComponent(signInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInUsernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInSubmitButton)
                    .addComponent(backButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab2", signInPanel);

        signUpPanel.setBackground(new java.awt.Color(0, 0, 48));
        signUpPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signUpPanel.setDoubleBuffered(false);
        signUpPanel.setPreferredSize(new java.awt.Dimension(500, 250));

        signUpTitle.setFont(new java.awt.Font("Montserrat Black", 1, 27)); // NOI18N
        signUpTitle.setForeground(new java.awt.Color(210, 210, 215));
        signUpTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signUpTitle.setText("Sign Up");

        signUpPasswordLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        signUpPasswordLabel.setForeground(new java.awt.Color(210, 210, 215));
        signUpPasswordLabel.setText("Password:");

        signUpPasswordTextfield.setBackground(new java.awt.Color(210, 210, 215));
        signUpPasswordTextfield.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        signUpPasswordTextfield.setForeground(new java.awt.Color(38, 38, 38));
        signUpPasswordTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpPasswordTextfieldActionPerformed(evt);
            }
        });

        signUpSubmitButton.setBackground(new java.awt.Color(89, 228, 147));
        signUpSubmitButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        signUpSubmitButton.setForeground(new java.awt.Color(38, 38, 38));
        signUpSubmitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        signUpSubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signUpSubmitButton.setLabel("Submit");
        signUpSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpSubmitButtonActionPerformed(evt);
            }
        });

        signUpUsernameLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        signUpUsernameLabel.setForeground(new java.awt.Color(210, 210, 215));
        signUpUsernameLabel.setText("Name:");

        signUpUsernameTextField.setBackground(new java.awt.Color(210, 210, 215));
        signUpUsernameTextField.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        signUpUsernameTextField.setForeground(new java.awt.Color(38, 38, 38));
        signUpUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpUsernameTextFieldActionPerformed(evt);
            }
        });

        nameTextField.setBackground(new java.awt.Color(210, 210, 215));
        nameTextField.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(38, 38, 38));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        signUpUsernameLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        signUpUsernameLabel1.setForeground(new java.awt.Color(210, 210, 215));
        signUpUsernameLabel1.setText("Username: ");

        backButton2.setBackground(new java.awt.Color(236, 172, 116));
        backButton2.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        backButton2.setForeground(new java.awt.Color(38, 38, 38));
        backButton2.setText("Back");
        backButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        backButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(signUpUsernameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signUpUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(signUpUsernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(signUpPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signUpPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(signUpSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(signUpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addComponent(signUpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jTabbedPane.addTab("tab3", signUpPanel);

        isAMemberOfFamilyPanel.setBackground(new java.awt.Color(0, 0, 48));
        isAMemberOfFamilyPanel.setPreferredSize(new java.awt.Dimension(500, 250));

        isAMemberOfFamilyCreateButton.setBackground(new java.awt.Color(89, 228, 147));
        isAMemberOfFamilyCreateButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        isAMemberOfFamilyCreateButton.setForeground(new java.awt.Color(38, 38, 38));
        isAMemberOfFamilyCreateButton.setText("Create");
        isAMemberOfFamilyCreateButton.setPreferredSize(new java.awt.Dimension(70, 40));
        isAMemberOfFamilyCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAMemberOfFamilyCreateButtonActionPerformed(evt);
            }
        });

        isAMemberOfFamilyJoinButton.setBackground(new java.awt.Color(89, 228, 147));
        isAMemberOfFamilyJoinButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        isAMemberOfFamilyJoinButton.setForeground(new java.awt.Color(38, 38, 38));
        isAMemberOfFamilyJoinButton.setText("Join");
        isAMemberOfFamilyJoinButton.setPreferredSize(new java.awt.Dimension(70, 40));
        isAMemberOfFamilyJoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAMemberOfFamilyJoinButtonActionPerformed(evt);
            }
        });

        isAMemberOfFamilyTitle1.setFont(new java.awt.Font("Montserrat Black", 2, 24)); // NOI18N
        isAMemberOfFamilyTitle1.setForeground(new java.awt.Color(210, 210, 215));
        isAMemberOfFamilyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isAMemberOfFamilyTitle1.setText("Do you want to...");

        isAMemberOfFamilyTitle2.setFont(new java.awt.Font("Montserrat Black", 2, 27)); // NOI18N
        isAMemberOfFamilyTitle2.setForeground(new java.awt.Color(210, 210, 215));
        isAMemberOfFamilyTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isAMemberOfFamilyTitle2.setText("a family?");

        isAMemberOfFamilyTitle3.setFont(new java.awt.Font("Montserrat", 2, 27)); // NOI18N
        isAMemberOfFamilyTitle3.setForeground(new java.awt.Color(210, 210, 215));
        isAMemberOfFamilyTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isAMemberOfFamilyTitle3.setText("or");

        backButtonToSignUp.setBackground(new java.awt.Color(210, 210, 215));
        backButtonToSignUp.setFont(new java.awt.Font("Montserrat", 3, 12)); // NOI18N
        backButtonToSignUp.setForeground(new java.awt.Color(38, 38, 38));
        backButtonToSignUp.setLabel("Go Back");
        backButtonToSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonToSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout isAMemberOfFamilyPanelLayout = new javax.swing.GroupLayout(isAMemberOfFamilyPanel);
        isAMemberOfFamilyPanel.setLayout(isAMemberOfFamilyPanelLayout);
        isAMemberOfFamilyPanelLayout.setHorizontalGroup(
            isAMemberOfFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isAMemberOfFamilyPanelLayout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(isAMemberOfFamilyJoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(isAMemberOfFamilyTitle3)
                .addGap(57, 57, 57)
                .addComponent(isAMemberOfFamilyCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(isAMemberOfFamilyPanelLayout.createSequentialGroup()
                .addGroup(isAMemberOfFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isAMemberOfFamilyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButtonToSignUp)
                        .addGap(37, 37, 37)
                        .addComponent(isAMemberOfFamilyTitle1))
                    .addGroup(isAMemberOfFamilyPanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(isAMemberOfFamilyTitle2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        isAMemberOfFamilyPanelLayout.setVerticalGroup(
            isAMemberOfFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isAMemberOfFamilyPanelLayout.createSequentialGroup()
                .addGroup(isAMemberOfFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isAMemberOfFamilyTitle1)
                    .addComponent(backButtonToSignUp))
                .addGap(29, 29, 29)
                .addGroup(isAMemberOfFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isAMemberOfFamilyJoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isAMemberOfFamilyTitle3)
                    .addComponent(isAMemberOfFamilyCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(isAMemberOfFamilyTitle2)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab4", isAMemberOfFamilyPanel);

        joinFamilyPanel.setBackground(new java.awt.Color(0, 0, 48));
        joinFamilyPanel.setPreferredSize(new java.awt.Dimension(500, 250));

        joinFamilyTitle.setFont(new java.awt.Font("Montserrat Black", 1, 27)); // NOI18N
        joinFamilyTitle.setForeground(new java.awt.Color(210, 210, 215));
        joinFamilyTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        joinFamilyTitle.setText("Join a Family");

        joinFamilySubmitButton.setBackground(new java.awt.Color(89, 228, 147));
        joinFamilySubmitButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        joinFamilySubmitButton.setForeground(new java.awt.Color(38, 38, 38));
        joinFamilySubmitButton.setLabel("Submit");
        joinFamilySubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinFamilySubmitButtonActionPerformed(evt);
            }
        });

        joinFamilyIDLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        joinFamilyIDLabel.setForeground(new java.awt.Color(210, 210, 215));
        joinFamilyIDLabel.setText("Family ID:");

        joinFamilyIDTextfield.setBackground(new java.awt.Color(210, 210, 215));
        joinFamilyIDTextfield.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        joinFamilyIDTextfield.setForeground(new java.awt.Color(38, 38, 38));
        joinFamilyIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinFamilyIDTextfieldActionPerformed(evt);
            }
        });

        backButtonToQuestion.setBackground(new java.awt.Color(236, 172, 116));
        backButtonToQuestion.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        backButtonToQuestion.setForeground(new java.awt.Color(38, 38, 38));
        backButtonToQuestion.setText("Back");
        backButtonToQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonToQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinFamilyPanelLayout = new javax.swing.GroupLayout(joinFamilyPanel);
        joinFamilyPanel.setLayout(joinFamilyPanelLayout);
        joinFamilyPanelLayout.setHorizontalGroup(
            joinFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinFamilyPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(joinFamilyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinFamilyPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(joinFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(joinFamilyPanelLayout.createSequentialGroup()
                        .addComponent(backButtonToQuestion)
                        .addGap(18, 18, 18)
                        .addComponent(joinFamilySubmitButton))
                    .addGroup(joinFamilyPanelLayout.createSequentialGroup()
                        .addComponent(joinFamilyIDLabel)
                        .addGap(44, 44, 44)
                        .addComponent(joinFamilyIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        joinFamilyPanelLayout.setVerticalGroup(
            joinFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinFamilyPanelLayout.createSequentialGroup()
                .addComponent(joinFamilyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(joinFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinFamilyIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinFamilyIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(joinFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinFamilySubmitButton)
                    .addComponent(backButtonToQuestion))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab5", joinFamilyPanel);

        createFamilyPanel.setBackground(new java.awt.Color(0, 0, 48));
        createFamilyPanel.setPreferredSize(new java.awt.Dimension(500, 250));

        createFamilySubmitButton.setBackground(new java.awt.Color(89, 228, 147));
        createFamilySubmitButton.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        createFamilySubmitButton.setForeground(new java.awt.Color(38, 38, 38));
        createFamilySubmitButton.setLabel("Submit");
        createFamilySubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFamilySubmitButtonActionPerformed(evt);
            }
        });

        createFamilyTitle.setFont(new java.awt.Font("Montserrat Black", 1, 27)); // NOI18N
        createFamilyTitle.setForeground(new java.awt.Color(210, 210, 215));
        createFamilyTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createFamilyTitle.setText("Create a Family");

        createFamilyNameLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        createFamilyNameLabel.setForeground(new java.awt.Color(210, 210, 215));
        createFamilyNameLabel.setText("Family Name:");

        createFamilyNameLabelTextfield.setBackground(new java.awt.Color(210, 210, 215));
        createFamilyNameLabelTextfield.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        createFamilyNameLabelTextfield.setForeground(new java.awt.Color(38, 38, 38));
        createFamilyNameLabelTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFamilyNameLabelTextfieldActionPerformed(evt);
            }
        });

        buttonBackToQuestion.setBackground(new java.awt.Color(236, 172, 116));
        buttonBackToQuestion.setFont(new java.awt.Font("Montserrat Black", 2, 18)); // NOI18N
        buttonBackToQuestion.setForeground(new java.awt.Color(38, 38, 38));
        buttonBackToQuestion.setText("Back");
        buttonBackToQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackToQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createFamilyPanelLayout = new javax.swing.GroupLayout(createFamilyPanel);
        createFamilyPanel.setLayout(createFamilyPanelLayout);
        createFamilyPanelLayout.setHorizontalGroup(
            createFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createFamilyPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(createFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createFamilyPanelLayout.createSequentialGroup()
                        .addComponent(buttonBackToQuestion)
                        .addGap(18, 18, 18)
                        .addComponent(createFamilySubmitButton))
                    .addGroup(createFamilyPanelLayout.createSequentialGroup()
                        .addComponent(createFamilyNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createFamilyNameLabelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(createFamilyPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(createFamilyTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        createFamilyPanelLayout.setVerticalGroup(
            createFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createFamilyPanelLayout.createSequentialGroup()
                .addComponent(createFamilyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(createFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createFamilyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createFamilyNameLabelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(createFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createFamilySubmitButton)
                    .addComponent(buttonBackToQuestion))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab6", createFamilyPanel);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
       jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
        //sign in panel
        
       
        jTabbedPane.setSelectedIndex(1);
        
    }//GEN-LAST:event_signInButtonActionPerformed

    private void signInSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInSubmitButtonActionPerformed
        try {
            // TODO add your handling code here:
            if (signInUsernameTextfield.getText().length() <= 0 || signInPasswordTextfield.getText().length() <= 0){ 
                
                JOptionPane.showMessageDialog(this, "Invalid Input Try Again"); 
                
            } else { 
            
                signInUN = signInUsernameTextfield.getText();
                signInPass = signInPasswordTextfield.getText();

                fm.login(signInUN, signInPass);
                if (fm.getMemberIsExisting()){
                    new NewJFrame(fm).setVisible(true);
                    this.setVisible(false); 
                    this.dispose(); 
                }

                else
                    JOptionPane.showMessageDialog(this, "Invalid Username or Password");

            
            
            }   
           
        } catch (SQLException ex) {
            Logger.getLogger(OpenJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        
    }//GEN-LAST:event_signInSubmitButtonActionPerformed
  
    private void signUpSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpSubmitButtonActionPerformed
        // TODO add your handling code here:
        
        if (nameTextField.getText().length() <= 0 || signUpUsernameTextField.getText().length() <= 0 || signUpPasswordTextfield.getText().length() <= 0){
            
            JOptionPane.showMessageDialog(this, "Invalid Input Try Again");
            
        } else{ 
            
            signName = nameTextField.getText();
            signUpUN = signUpUsernameTextField.getText();
            signUpPass = signUpPasswordTextfield.getText();
            fm = new FamilyMember(signName, signUpUN, signUpPass);
        
            if (fm.getMember_alreadyExisting())
                JOptionPane.showMessageDialog(this, "Username is already taken");
            else 
                jTabbedPane.setSelectedIndex(3);
            
            
        }
        
        
        
      
    }//GEN-LAST:event_signUpSubmitButtonActionPerformed

    private void isAMemberOfFamilyCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAMemberOfFamilyCreateButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(5);
    }//GEN-LAST:event_isAMemberOfFamilyCreateButtonActionPerformed

    private void joinFamilySubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinFamilySubmitButtonActionPerformed
        
        
        try {
            // TODO add your handling code here:
            if (joinFamilyIDTextfield.getText().length() <= 0 || Integer.parseInt(joinFamilyIDTextfield.getText()) < 0){
                JOptionPane.showMessageDialog(this, "Invalid Input Try Again"); 
            } else { 
            
                joinFamID = joinFamilyIDTextfield.getText();
                fm.joinFamily(Integer.parseInt(joinFamID), null);
                if (fm.getFamilyIsExisting()){
                   new NewJFrame(fm).setVisible(true);
                   this.dispose();
                   this.setVisible(false);
                } 
                else
                   JOptionPane.showMessageDialog(this, "Family Doesn't Exist. Try Again.");

            }
  
          
        } catch (SQLException ex) {
            Logger.getLogger(OpenJframe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException exe){ 
            JOptionPane.showMessageDialog(this, "Invalid Input Try Again");
        }
        
       
        
    }//GEN-LAST:event_joinFamilySubmitButtonActionPerformed

    private void isAMemberOfFamilyJoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAMemberOfFamilyJoinButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(4);
        
    }//GEN-LAST:event_isAMemberOfFamilyJoinButtonActionPerformed

    private void createFamilySubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFamilySubmitButtonActionPerformed
        try {
            // TODO add your handling code here:
            
            if (createFamilyNameLabelTextfield.getText().length() <= 0){
                
                JOptionPane.showMessageDialog(this, "Invalid Input Try Again");
                
                
            } else {
            
                createFamName = createFamilyNameLabelTextfield.getText();
                fm.createFamily(createFamName);
                if (fm.getFam_alreadyExisting())
                    JOptionPane.showMessageDialog(this, "Family Name is Already Existing");
                else{
                    new NewJFrame(fm).setVisible(true);
                    this.dispose();
                    this.setVisible(false);
                   
                 
                }
                
            }
            
            
            
            
               
              
        } catch (SQLException ex) {
            Logger.getLogger(OpenJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_createFamilySubmitButtonActionPerformed

    private void signInUsernameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInUsernameTextfieldActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_signInUsernameTextfieldActionPerformed

    private void signInPasswordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInPasswordTextfieldActionPerformed
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_signInPasswordTextfieldActionPerformed

    private void signUpUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpUsernameTextFieldActionPerformed
        // TODO add your handling code here:
      //add here
    }//GEN-LAST:event_signUpUsernameTextFieldActionPerformed

    private void signUpPasswordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpPasswordTextfieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_signUpPasswordTextfieldActionPerformed
   
    private void joinFamilyIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinFamilyIDTextfieldActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_joinFamilyIDTextfieldActionPerformed
  
    private void createFamilyNameLabelTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFamilyNameLabelTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_createFamilyNameLabelTextfieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameTextFieldActionPerformed
     
    

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        // exit button
        
        System.out.print("Program Terminated");
        System.exit(0);

    }//GEN-LAST:event_exitButtonActionPerformed

   
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
       jTabbedPane.setSelectedIndex(0); 
       signInUsernameTextfield.setText("");
       signInPasswordTextfield.setText("");
        
                
    }//GEN-LAST:event_backButtonActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(0); 
        
        nameTextField.setText("");
        signUpUsernameTextField.setText("");
        signUpPasswordTextfield.setText("");
    }//GEN-LAST:event_backButton2ActionPerformed

    private void backButtonToSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonToSignUpActionPerformed
        // TODO add your handling code here:
         jTabbedPane.setSelectedIndex(2); 
    }//GEN-LAST:event_backButtonToSignUpActionPerformed

    private void backButtonToQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonToQuestionActionPerformed
        // TODO add your handling code here:
       
        jTabbedPane.setSelectedIndex(3);
        joinFamilyIDTextfield.setText("");
    }//GEN-LAST:event_backButtonToQuestionActionPerformed

    private void buttonBackToQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackToQuestionActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(3);
        createFamilyNameLabelTextfield.setText("");
    }//GEN-LAST:event_buttonBackToQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenJframe().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButtonToQuestion;
    private javax.swing.JButton backButtonToSignUp;
    private javax.swing.JButton buttonBackToQuestion;
    private javax.swing.JLabel createFamilyNameLabel;
    private javax.swing.JTextField createFamilyNameLabelTextfield;
    private javax.swing.JPanel createFamilyPanel;
    private javax.swing.JButton createFamilySubmitButton;
    private javax.swing.JLabel createFamilyTitle;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel hideTabPanel;
    private javax.swing.JButton isAMemberOfFamilyCreateButton;
    private javax.swing.JButton isAMemberOfFamilyJoinButton;
    private javax.swing.JPanel isAMemberOfFamilyPanel;
    private javax.swing.JLabel isAMemberOfFamilyTitle1;
    private javax.swing.JLabel isAMemberOfFamilyTitle2;
    private javax.swing.JLabel isAMemberOfFamilyTitle3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel joinFamilyIDLabel;
    private javax.swing.JTextField joinFamilyIDTextfield;
    private javax.swing.JPanel joinFamilyPanel;
    private javax.swing.JButton joinFamilySubmitButton;
    private javax.swing.JLabel joinFamilyTitle;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel openAppPanel;
    private javax.swing.JLabel openTitleText;
    private javax.swing.JButton signInButton;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JTextField signInPasswordTextfield;
    private javax.swing.JButton signInSubmitButton;
    private javax.swing.JLabel signInTitle;
    private javax.swing.JLabel signInUsernameLabel;
    private javax.swing.JLabel signInUsernameLabel1;
    private javax.swing.JTextField signInUsernameTextfield;
    private javax.swing.JButton signUpButton;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signUpPasswordLabel;
    private javax.swing.JTextField signUpPasswordTextfield;
    private javax.swing.JButton signUpSubmitButton;
    private javax.swing.JLabel signUpTitle;
    private javax.swing.JLabel signUpUsernameLabel;
    private javax.swing.JLabel signUpUsernameLabel1;
    private javax.swing.JTextField signUpUsernameTextField;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables

// Round Borders
    
class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
